### ISSUE TITLE
Animals only spawning in the start Region

### ISSUE THREAD

**Issue by Koopus2000** [Filigrani/SkyCoop#23]
I have noticed while playing with a friend that after leaving our starting region, Pleasant valley and heading to Timberwolf mountain, there were no animals spawning in the new region we transitioned to. Reloading game did not fix. Can confirm it is a mod issue as swapping back to vanilla long dark fixes the issue.

**Comment by Filigrani** [comment]
Thanks! Sorry for big delay, usually I not paying much attention on git, because most active going on our discord, but I plan to fully move all bug tracking to git soon.

**Comment by Filigrani** [comment]
What experience mode it was?

**Comment by Filigrani** [comment]
![Image](https://user-images.githubusercontent.com/21259421/190492119-14d15f77-26ca-4b7c-874f-c33967b2ae98.png)

Test done on Steam P2P, starting region is Pleasant valley, without console, in real time walked to Timberwolf mountain, in first second we did not spot any animals, but after while, we have found some rabbits, deer and wolfs when got to the mountaineer hunt. Expereince mode was Stalker, mod version is 10.1. So we wasn't able to reproduce this bug. Maybe you can try encount this problem on latest version (10.1), if so please sumbit it as new issue, because we prepared handy form for that.
