### ISSUE TITLE
Game freezes and crashes on menu

### ISSUE THREAD

**Issue by Lussian-A** [Filigrani/SkyCoop#26]
**Mod Version:** v0.10.3
**Game Version:** v2.02 
**Launcher:** Steam
**Additional mods installed:** Both with additonal and without "aka" clean install.
**Perspective:** Host - Haven't tried client as can't start the game.

### Description
Launching the game and when I get to the menu every thing requires 2-3 clicks to enter while the melonload log spams error messages and if I enter the multiplayer menu it's empty and the game freezes and crashes after a little while.

### How to reproduce

Pointing to above.

### Expected behavior
I'd expect it to launch like 9.x did 
and I assume this is something known if not and you can't reproduce then different drivers of some kind?

### Logs

**Host side log**
```
Attaching log file. 
```

[MelonLoader_22-09-23_15-39-48.157.log](https://github.com/Filigrani/SkyCoop/files/9634162/MelonLoader_22-09-23_15-39-48.157.log)

**Comment by Filigrani** [comment]
Incorrect plugins files, please delete whole "Plugins" folder, and start the game, mod will recover missing plugins, this seems like more crash on my side than on your, because this happends cause you have one plugin but not another, but mod only can recover them if they both are missing. So, just delete "Plugins" folder and it should work. I almost sure it will help, but still PLEASE, leave a comment after you done, so I will be sure to close this issue.

**Comment by Lussian-A** [comment]
Ah you were correct. Deleting the plugins folder worked. Thanks.

**Comment by Filigrani** [comment]
Thanks for letting us about problem, it will be fixed in next patch!
