### ISSUE TITLE
Gears from other mods does not load, if corrupted SkyCoop.modcomponent is present.

### ISSUE THREAD

**Issue by MinimalSix** [Filigrani/SkyCoop#33]
**Mod Version:** v0.10.4
**Game Version:** v2.02
**Launcher:** Steam
**Additional mods installed:**  Yes (several mods that add items, tested with no other mods installed)
**Perspective:** Host

### Description
Mods that have additional items will still spawn them throughout the world, however they do not have a name on screen, and cannot be interacted with. Loading a save made prior to the install of SkyCoop removes all mod items dropped by the player. The missing items cannot be added to the player inventory from the developer console either. Mod items that should be added to inventory with item breakdown (ex: wrought nails from DIY), are added floating in scene, and disappear on scene reload

Some examples of broken items from my mod list:

Candles (Candlelight by DigitalZombie)
Furniture (DIY by Santana)
Gas cans (Better Fuel Management by ds5678)
Ammo boxes/gunpowder (Cannery Manufacturing by ds5678)

Mod items that do still work:
Shortwave Radio (from this mod)
Patchwork blanket (Blanket mod by ds5678)

### How to reproduce
Create a new world with mod items, most aren't usable. Load world from before installation of SkyCoop, mod items disappear. 

### Log & Screenshot

[MelonLoader_22-10-07_18-12-45.179.log](https://github.com/Filigrani/SkyCoop/files/9738112/MelonLoader_22-10-07_18-12-45.179.log)

the perspective doesn't show well, but these nails are well within the interaction range, but cannot be selected
![Floating_nails](https://user-images.githubusercontent.com/115326852/194680768-bda243f9-f871-4d1b-a8f2-a81c895b6e1d.png)

**Comment by Filigrani** [comment]
Hm. Looks like problem on my side. But I was almost sure it works when I checked this day ago. Try to delete SkyCoop.modcomponent file and check if it helps. This file only has medkits that useless right now. In one update I accidetly unload broken .modcomponent file so that why it happens. Modcomponent isnt mine mod so I not sure if problem with my .modcomponent cant affect on loading other ones you have, this what I want you to try. Delete SkyCoop.modcomponent, and check if peoblem is solved, if not I will going to make more careful invistigation.

**Comment by MinimalSix** [comment]
Yes, deleting the SkyCoop.modcomponent file solved this issue

**Comment by Filigrani** [comment]
Okay, on next release it going to fixed, because SkyCoop.modcomponent will not be corrupted. But you should know that deleting with SkyCoop.modcomponent, you also can't hear other player's gun shots, because there was custom 3d sounds for that, but I think this not a big close. So you can play that way until I release update with not corrupted SkyCoop.modcomponent file.

**Comment by Filigrani** [comment]
Fixed in latest release.
