### ISSUE TITLE
Lantern freeze at use and oil diseppearing

### ISSUE THREAD

**Issue by Scotvince** [Filigrani/SkyCoop#44]
**Mod Version:** v0.10.4
**Game Version:** v2.02 
**Launcher:** Steam  
**Additional mods installed:** No
**Perspective:** Host/Client 

### Description
I want to report several bugs:

1. When I click to start the lantern, the lantern freeze. Then I sheathe it. I verify into the inventory, and all the lamp oil has vanished. 

2. I also experimented clothes disappearing when get dropped on the floor (on carpets); and also when clothes I discovered into furniture, don't choose to take it, let there in it: when I retry to take into this furniture, the cloth has disappeared.

3. When I put a item on a surface other than the floor, my teammate cannot take it (even don't see it). It's not happen all the time.
[MelonLoader_22-11-27_21-49-13.033.log](https://github.com/Filigrani/SkyCoop/files/10104005/MelonLoader_22-11-27_21-49-13.033.log)

4. I am not sure if it is a bug, but when I use a place on the fire for cooking, my teammate don't see anything on that fire. And of course can't take it.

5. The fire indicates how much time remains. My teammate  doesn't see the same time as me.

### How to reproduce
1. Being host/client.
2. On region 'CoastalHighway'
4. Do  'use the lantern'
3. It works wrong / it wasn't working.

### Expected behavior
If not obvious, what did you expect to happen?

### Logs

**Host side log**
```
Paste crash between the triple backticks.

Log can be found in game directory "TheLongDark\MelonLoader\Logs", please make sure that you paste CORRECT LOG, every log named with date of session, so please paste log only from session where you exactly had a problem.

If you are the client of a session, please ask your friend host to send you a log file. (Even if only client(s) experienced the problem, a host log is required in any way).
```
**Client side log**
```
Paste crash between the triple backticks.

Log can be found in game directory "TheLongDark\MelonLoader\Logs", please make sure that you paste CORRECT LOG, every log named with date of session, so please paste log only from session where you exactly had a problem.

If you are the host of the session, please ask your friend(s) client(s) that experienced a problem, to send their logs to you.
```

**Comment by Filigrani** [comment]
1. Can't reproduce, works correctly on my setup. Maybe problem because of incorrect time on the clinet side? Give me save file, so can try to reproduce once again.
2. Can't reproduce, works correctly on my setup. Need more information, because I can't even imagine how to trigger this, and you noted that it works only with clothing, but every gear works the same when dropped.
3. Can't reproduce, works correctly on my setup. No information about examples of "non" floor surfaces.
4. Works as intended.
5. Works as intended, FAQ 5. Fule and cooking on local timeline to avoid abuse and realtime cooking.
6.

**Comment by Filigrani** [comment]
Can't reproduce.
